#!/bin/bash

# GPU
echo "using GPU - Run $run"
for qp in 17 22 27 32 37; do
    python  /code/codes/benchmark_complexity.py -opt /code/codes/options/test_septuplet/test_TVRN_compress_temporal_epm_old_restoration_unified.yml -staa_opt /code/codes/options/test/test_STAA.yml -path /data/fengxm/vimeo90k/snufilm_test/test/ -mode cqp -model TVRN -qp $qp --checkpoints /model/fengxm/VRN/MIMO_VRN/MIMO_TVRN_codec_restoration_unified_restoration_adaptor/60000_G.pth --codec_type hevc --gpu_id 0 --record_time True 
    python  /code/codes/benchmark_complexity.py -opt /code/codes/options/test_septuplet/test_TVRN_compress_temporal_epm_old_restoration_unified.yml -staa_opt /code/codes/options/test/test_STAA.yml -path /data/fengxm/vimeo90k/snufilm_test/test/ -mode cqp -model TVRN_S -qp $qp --checkpoints /model/fengxm/VRN/MIMO_VRN/MIMO_TVRN_codec_restoration_unified_restoration_adaptor/60000_G.pth --codec_type hevc --gpu_id 0 --record_time True 
    python  /code/codes/benchmark_complexity.py -opt /code/codes/options/test_septuplet/test_TVRN_compress_temporal_epm_old_restoration_unified.yml -staa_opt /code/codes/options/test/test_STAA.yml -path /data/fengxm/vimeo90k/snufilm_test/test/ -mode cqp -model IFRNet -qp $qp --checkpoints /model/fengxm/VRN/MIMO_VRN/MIMO_TVRN_codec_restoration_unified_restoration_adaptor/60000_G.pth --codec_type hevc --gpu_id 0 --record_time True 
    python  /code/codes/benchmark_complexity.py -opt /code/codes/options/test_septuplet/test_TVRN_compress_temporal_epm_old_restoration_unified.yml -staa_opt /code/codes/options/test/test_STAA.yml -path /data/fengxm/vimeo90k/snufilm_test/test/ -mode cqp -model EBME -qp $qp --checkpoints /model/fengxm/VRN/MIMO_VRN/MIMO_TVRN_codec_restoration_unified_restoration_adaptor/60000_G.pth --codec_type hevc --gpu_id 0 --record_time True 
    python  /code/codes/benchmark_complexity.py -opt /code/codes/options/test_septuplet/test_TVRN_compress_temporal_epm_old_restoration_unified.yml -staa_opt /code/codes/options/test/test_STAA.yml -path /data/fengxm/vimeo90k/snufilm_test/test/ -mode cqp -model STAA -qp $qp --checkpoints /model/fengxm/VRN/MIMO_VRN/MIMO_TVRN_codec_restoration_unified_restoration_adaptor/60000_G.pth --codec_type hevc --gpu_id 0 --record_time True 
    python  /code/codes/benchmark_complexity.py -opt /code/codes/options/test_septuplet/test_TVRN_compress_temporal_epm_old_restoration_unified.yml -staa_opt /code/codes/options/test/test_STAA.yml -path /data/fengxm/vimeo90k/snufilm_test/test/ -mode cqp -model GIMM -qp $qp --checkpoints /model/fengxm/VRN/MIMO_VRN/MIMO_TVRN_codec_restoration_unified_restoration_adaptor/60000_G.pth --codec_type hevc --gpu_id 0 --record_time True 
    python  /code/codes/benchmark_complexity.py -opt /code/codes/options/test_septuplet/test_TVRN_compress_temporal_epm_old_restoration_unified.yml -staa_opt /code/codes/options/test/test_STAA.yml -path /data/fengxm/vimeo90k/snufilm_test/test/ -mode cqp -model RIFE -qp $qp --checkpoints /model/fengxm/VRN/MIMO_VRN/MIMO_TVRN_codec_restoration_unified_restoration_adaptor/60000_G.pth --codec_type hevc --gpu_id 0 --record_time True 
done
# cpu
echo "using CPU - Run $run"

python  /code/codes/benchmark_complexity.py -opt /code/codes/options/test_septuplet/test_TVRN_compress_temporal_epm_old_restoration_unified.yml -staa_opt /code/codes/options/test/test_STAA.yml -path /data/fengxm/vimeo90k/snufilm_test/test/ -mode cqp -model TVRN -qp 18 --checkpoints /model/fengxm/VRN/MIMO_VRN/MIMO_TVRN_codec_restoration_unified_restoration_adaptor/60000_G.pth --codec_type hevc --gpu_id -1 --record_time True --cpu True
python  /code/codes/benchmark_complexity.py -opt /code/codes/options/test_septuplet/test_TVRN_compress_temporal_epm_old_restoration_unified.yml -staa_opt /code/codes/options/test/test_STAA.yml -path /data/fengxm/vimeo90k/snufilm_test/test/ -mode cqp -model TVRN_S -qp 18 --checkpoints /model/fengxm/VRN/MIMO_VRN/MIMO_TVRN_codec_restoration_unified_restoration_adaptor/60000_G.pth --codec_type hevc --gpu_id -1 --record_time True --cpu True
python  /code/codes/benchmark_complexity.py -opt /code/codes/options/test_septuplet/test_TVRN_compress_temporal_epm_old_restoration_unified.yml -staa_opt /code/codes/options/test/test_STAA.yml -path /data/fengxm/vimeo90k/snufilm_test/test/ -mode cqp -model IFRNet -qp 18 --checkpoints /model/fengxm/VRN/MIMO_VRN/MIMO_TVRN_codec_restoration_unified_restoration_adaptor/60000_G.pth --codec_type hevc --gpu_id -1 --record_time True --cpu True
python  /code/codes/benchmark_complexity.py -opt /code/codes/options/test_septuplet/test_TVRN_compress_temporal_epm_old_restoration_unified.yml -staa_opt /code/codes/options/test/test_STAA.yml -path /data/fengxm/vimeo90k/snufilm_test/test/ -mode cqp -model EBME -qp 18 --checkpoints /model/fengxm/VRN/MIMO_VRN/MIMO_TVRN_codec_restoration_unified_restoration_adaptor/60000_G.pth --codec_type hevc --gpu_id -1 --record_time True --cpu True
python  /code/codes/benchmark_complexity.py -opt /code/codes/options/test_septuplet/test_TVRN_compress_temporal_epm_old_restoration_unified.yml -staa_opt /code/codes/options/test/test_STAA.yml -path /data/fengxm/vimeo90k/snufilm_test/test/ -mode cqp -model STAA -qp 18 --checkpoints /model/fengxm/VRN/MIMO_VRN/MIMO_TVRN_codec_restoration_unified_restoration_adaptor/60000_G.pth --codec_type hevc --gpu_id -1 --record_time True --cpu True
python  /code/codes/benchmark_complexity.py -opt /code/codes/options/test_septuplet/test_TVRN_compress_temporal_epm_old_restoration_unified.yml -staa_opt /code/codes/options/test/test_STAA.yml -path /data/fengxm/vimeo90k/snufilm_test/test/ -mode cqp -model GIMM -qp 18 --checkpoints /model/fengxm/VRN/MIMO_VRN/MIMO_TVRN_codec_restoration_unified_restoration_adaptor/60000_G.pth --codec_type hevc --gpu_id -1 --record_time True --cpu True
python  /code/codes/benchmark_complexity.py -opt /code/codes/options/test_septuplet/test_TVRN_compress_temporal_epm_old_restoration_unified.yml -staa_opt /code/codes/options/test/test_STAA.yml -path /data/fengxm/vimeo90k/snufilm_test/test/ -mode cqp -model RIFE -qp 18 --checkpoints /model/fengxm/VRN/MIMO_VRN/MIMO_TVRN_codec_restoration_unified_restoration_adaptor/60000_G.pth --codec_type hevc --gpu_id -1 --record_time True --cpu True
